"""Generated offline model catalog; edit models.json, then run build_dist.py."""
MODEL_CATALOG = {'personal-general': {'default': 'tc-code-latest',
                      'display': ['Auto 智能路由: tc-code-latest',
                                  'DeepSeek-V4-Flash: deepseek-v4-flash-202605',
                                  'DeepSeek-V4-Pro: deepseek-v4-pro-202606',
                                  'MiniMax-M2.7: minimax-m2.7',
                                  'MiniMax-M3: minimax-m3',
                                  'GLM-5: glm-5',
                                  'GLM-5.1: glm-5.1',
                                  'GLM-5.2: glm-5.2',
                                  'GLM-5.3: glm-5.3',
                                  'Kimi-K2.7-Code: kimi-k2.7-code',
                                  '混元 Hy3: hy3',
                                  '混元 Hy4-preview: hy4-preview',
                                  '混元 Hy3-preview: hy3-preview',
                                  '混元 Hy3-202608: hy3-202608']},
 'personal-hy': {'default': 'hy3',
                 'display': ['Hy3: hy3',
                             'Hy4-preview: hy4-preview',
                             'Hy3-preview: hy3-preview',
                             'Hy3-202608: hy3-202608']},
 'enterprise-pro': {'default': 'auto',
                    'display': ['Auto: auto',
                                'GLM-5.3: glm-5.3',
                                'GLM-5.2: glm-5.2',
                                'GLM-5: glm-5',
                                'GLM-5.1: glm-5.1',
                                'GLM-5-Turbo: glm-5-turbo',
                                'Kimi K2.7 Code: kimi-k2.7-code',
                                'HighSpeed: kimi-k2.7-code-highspeed',
                                'Kimi-K2.6: kimi-k2.6',
                                'MiniMax-M2.7: minimax-m2.7',
                                'MiniMax-M3: minimax-m3',
                                'DeepSeek-V4-Flash: deepseek-v4-flash',
                                'DeepSeek-V4-Pro: deepseek-v4-pro',
                                'DeepSeek-V4-Flash 0731 正式版: deepseek-v4-flash-0731',
                                'DeepSeek-V4-Pro 0813 正式版: deepseek-v4-pro-0813',
                                'DeepSeek-V4-Flash 正式版 原厂: deepseek-v4-flash-202605',
                                'Pro 原厂: deepseek-v4-pro-202606',
                                'Vision-Exp 原厂(多模态): deepseek/deepseek-v4-flash-vision-exp']},
 'enterprise-light': {'default': 'auto', 'display': ['Auto 智能路由: auto']},
 'intl-personal': {'default': 'auto',
                   'display': ['Auto 智能路由: auto',
                               'DeepSeek-V4-Flash: deepseek-v4-flash-202605',
                               'DeepSeek-V4-Pro: deepseek-v4-pro-202606',
                               'GLM-5.2: glm-5.2',
                               'Kimi-K2.6: kimi-k2.6',
                               'MiniMax-M3: minimax-m3']},
 'intl-enterprise-pro': {'default': 'auto',
                         'display': ['Auto: auto',
                                     'GLM-5.3: glm-5.3',
                                     'GLM-5.2: glm-5.2',
                                     'Kimi K2.7 Code: kimi-k2.7-code',
                                     'HighSpeed: kimi-k2.7-code-highspeed',
                                     'MiniMax-M3: minimax-m3',
                                     'DeepSeek-V4-Flash: deepseek-v4-flash',
                                     'DeepSeek-V4-Pro: deepseek-v4-pro',
                                     'DeepSeek-V4-Flash 0731 正式版: deepseek-v4-flash-0731',
                                     'DeepSeek-V4-Pro 0813 正式版: deepseek-v4-pro-0813',
                                     'DeepSeek-V4-Flash 正式版 原厂: deepseek-v4-flash-202605',
                                     'Pro 原厂: deepseek-v4-pro-202606',
                                     'Vision-Exp 原厂(多模态): deepseek/deepseek-v4-flash-vision-exp']},
 'intl-enterprise-light': {'default': 'auto', 'display': ['Auto 智能路由: auto']},
 'postpaid': {'default': '', 'display': []},
 'postpaid-intl': {'default': '', 'display': []}}
