#!/usr/bin/env python3
"""Deterministically build all standalone distribution artifacts.

``models.json`` is the human-maintained model source. This script generates its
offline Python representation, bundles package modules into ``setup.command``,
syncs the npm copy, and refreshes integrity metadata.
"""
import argparse
import hashlib
import json
import pprint
import re
import sys
from pathlib import Path
from typing import Dict

REPO = Path(__file__).resolve().parent.parent
PACKAGE = REPO / "tokenplan_setup"
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

# 必须先把仓库根加入 sys.path,本脚本才能在未安装包的情况下直接运行。
from tokenplan_setup._runtime import (  # noqa: E402
    SOURCE_ORDER,
    strip_internal_imports,
)

POLYGLOT_HEADER = (
    "#!/bin/bash\n"
    '"exec" "$(command -v python3 || command -v python)" "$0" "$@"\n'
    "# Generated by scripts/build_dist.py; edit tokenplan_setup/ instead.\n"
)


def project_version() -> str:
    text = (REPO / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(r'(?m)^version\s*=\s*"([^"]+)"\s*$', text)
    if not match:
        raise ValueError("project.version missing from pyproject.toml")
    return match.group(1)


def generated_model_catalog() -> bytes:
    data = json.loads((REPO / "models.json").read_text(encoding="utf-8"))
    plans = data.get("plans")
    if not isinstance(plans, dict):
        raise ValueError("models.json must contain an object named 'plans'")
    body = pprint.pformat(plans, width=100, sort_dicts=False)
    return (
        '"""Generated offline model catalog; edit models.json, then run build_dist.py."""\n'
        f"MODEL_CATALOG = {body}\n"
    ).encode("utf-8")


def bundled_script(generated_catalog: bytes) -> bytes:
    chunks = []
    for filename in SOURCE_ORDER:
        if filename == "_model_catalog.py":
            text = generated_catalog.decode("utf-8")
        else:
            text = (PACKAGE / filename).read_text(encoding="utf-8")
        chunks.append(strip_internal_imports(text))
    return (POLYGLOT_HEADER + "\n".join(chunks)).encode("utf-8")


def updated_bat(script: bytes, version: str) -> bytes:
    path = REPO / "setup.bat"
    text = path.read_bytes().decode("utf-8")
    digest = hashlib.sha256(script).hexdigest()
    text, version_count = re.subn(
        r'set "SETUP_VERSION=[^"]*"',
        f'set "SETUP_VERSION={version}"',
        text,
    )
    text, hash_count = re.subn(
        r'set "SETUP_SHA256=[^"]*"',
        f'set "SETUP_SHA256={digest}"',
        text,
    )
    if version_count != 1 or hash_count != 1:
        raise ValueError("setup.bat metadata markers missing or duplicated")
    # setup.bat 必须是 CRLF；否则 cmd 的兼容性与回归契约都会漂移。
    return text.replace("\r\n", "\n").replace("\n", "\r\n").encode("utf-8")


def expected_outputs() -> Dict[Path, bytes]:
    version = project_version()
    catalog_raw = (REPO / "models.json").read_bytes()
    catalog = json.loads(catalog_raw.decode("utf-8"))
    if catalog.get("latest_version") != version:
        raise ValueError(
            "models.json latest_version must match project.version "
            f"({catalog.get('latest_version')!r} != {version!r})"
        )
    npm = json.loads((REPO / "npm" / "package.json").read_text(encoding="utf-8"))
    if npm.get("version") != version:
        raise ValueError("npm/package.json version must match project.version")

    generated_catalog = generated_model_catalog()
    script = bundled_script(generated_catalog)
    catalog_digest = hashlib.sha256(catalog_raw).hexdigest()
    return {
        PACKAGE / "_model_catalog.py": generated_catalog,
        REPO / "setup.command": script,
        REPO / "npm" / "lib" / "setup.command": script,
        REPO / "models.json.sha256": f"{catalog_digest}  models.json\n".encode(),
        REPO / "setup.bat": updated_bat(script, version),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated files without modifying them",
    )
    args = parser.parse_args()

    outputs = expected_outputs()
    stale = [path for path, content in outputs.items() if not path.exists() or path.read_bytes() != content]
    if args.check:
        if stale:
            for path in stale:
                print(f"out of date: {path.relative_to(REPO)}", file=sys.stderr)
            return 1
        print(f"build check passed ({len(outputs)} artifacts)")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and path.read_bytes() == content:
            print(f"unchanged: {path.relative_to(REPO)}")
            continue
        path.write_bytes(content)
        print(f"generated: {path.relative_to(REPO)}")
    (REPO / "setup.command").chmod(0o755)
    (REPO / "npm" / "lib" / "setup.command").chmod(0o755)
    return 0


if __name__ == "__main__":
    sys.exit(main())
